POST http://localhost:8080/add_income
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg0MDI4OTUsInVzZXJfaWQiOjE2fQ.OqDgvvkegVg1zY1w3VEqDAmcesDVvtD6lsZXIW5EVbI

{
    "amount_usd": 5000.00,
    "trx_category": "Salary"
}