POST http://localhost:8080/add_expense
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg0OTA4NzQsInVzZXJfaWQiOjF9.OEmpktSKHQTikcj-BPMCaRgM7UIRWbGWBViiusX_MMA

{
    "amount_usd": 20,
    "trx_category": "Subscriptions"
}