POST http://localhost:8080/add_income
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDgwNjM0NzAsInVzZXJfaWQiOjE2fQ.4efUr307QBixdg0JN4cyyP2o8aV01nEibxW-1SnlM7U

{
    "amount_usd": 200.00,
    "trx_category": "Salary"
}