GET http://localhost:8080/transactions/date?from_date=2025-05-23&to_date=2025-05-26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg0MDkwNzAsInVzZXJfaWQiOjE2fQ.I4bm0TcSNotNawRAXNEpisAdcNHWxlegMtN4YzJVkVQ